In [2]:
import pennylane as qml
from pennylane import numpy as np

In [4]:
# Define the wires for the quantum circuit
wires = range(2)

# Create a PennyLane device for the quantum circuit
basic_dev = qml.device("default.qubit", wires=wires)

# Define a quantum circuit using the BasisEmbedding operation
@qml.qnode(basic_dev)
def basis_encoder(data):
    qml.BasisEmbedding(data, wires=wires)
    return qml.state()

In [5]:
basis_encoder(3)

tensor([0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j], requires_grad=True)

In [6]:
wires = range(2)
amp_dev = qml.device("default.qubit", wires=wires)


@qml.qnode(amp_dev)
def amp_encoder(data):
    qml.AmplitudeEmbedding(data, wires)
    return qml.state()

In [7]:
amp_encoder([0.5, 0.5, 0.5, 0.5])

tensor([0.5+0.j, 0.5+0.j, 0.5+0.j, 0.5+0.j], requires_grad=True)

When size is not equal to 2^n

In [8]:
wires = range(2)
amp_dev = qml.device("default.qubit", wires=wires)


@qml.qnode(amp_dev)
def amp_encoder(data):
    qml.AmplitudeEmbedding(data, wires, pad_with=0.0)
    return qml.state()

In [13]:
amp_encoder([1])

tensor([1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j], requires_grad=True)